name: Deploy to GitHub Pages

on:
    push:
        branches: [main]

jobs:
    deploy-to-github-pages:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4 # Updated to v4

            - name: Remove instructions page
              run: |
                  chmod +x ./src/Scripts/remove-instructions.sh  
                  bash ./src/Scripts/remove-instructions.sh
                  chmod +x ./src/Scripts/update-hrefs.sh  
                  bash ./src/Scripts/update-hrefs.sh "${{ github.repository }}"

            - name: Setup .NET Core
              uses: actions/setup-dotnet@v4 # Updated to v4 for .NET 10 support
              with:
                  dotnet-version: 10.0.x

            - name: Publish .NET Core Project
              run: dotnet publish src/Portfolio.csproj -c Release -o src/release --nologo

            # REMOVED the "Change base-tag" step because your site is at the root domain

            - name: copy index.html to 404.html
              run: cp src/release/wwwroot/index.html src/release/wwwroot/404.html

            - name: Add .nojekyll file
              run: touch src/release/wwwroot/.nojekyll

            - name: Commit wwwroot to GitHub Pages
              uses: JamesIves/github-pages-deploy-action@v4.4.1
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  branch: gh-pages
                  folder: src/release/wwwroot
